name: horizontal_indicator
description: This package let you add horizontal indicator with list view that you can show days with active bubble. You can even add this any where in the widget tree and also customize as you want.
version: 0.0.3
author: Asanka B.L. (Blasanka) <blasanka95@gmail.com>
homepage: https://github.com/Blasanka/horizontal_indicator/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
