name: horizontal_indicator
description: Package to add day of month with day of week as horizontal list with active bubbles.
version: 0.0.8
#author: Asanka B.L. (Blasanka) <blasanka95@yahoo.com>
homepage: https://github.com/Blasanka/horizontal_indicator/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
